### PR TITLE
chore(analytics): Add Google Analytics and Zoho Analytics tags

### PR DESCRIPTION
**Pull request by steve-gr4vy**
Add GA, GTag and Zoho analytics

### CODE REVIEW

**Review by cbetta — COMMENTED** [review]
1. Can you please check with Jeniffer and check if we need both the GTAG and GAnalytics tags, or just one. I forgot what she said.
2. The tags I sent you also included a <noscript> part. Is this missing on purpose?

**Comment by cbetta** [comment]
> 1. Can you please check with Jeniffer and check if we need both the GTAG and GAnalytics tags, or just one. I forgot what she said.
> 2. The tags I sent you also included a `<noscript>` part. Is this missing on purpose?

@steve-gr4vy did you follow up with Jennifer on this?

**Comment by steve-gr4vy** [comment]
> > 1. Can you please check with Jeniffer and check if we need both the GTAG and GAnalytics tags, or just one. I forgot what she said.
> > 2. The tags I sent you also included a `<noscript>` part. Is this missing on purpose?
> 
> @steve-gr4vy did you follow up with Jennifer on this?

1. Yes, Jennifer said: "Yes, only because I haven't had bandwidth to add GAnalytics to Gtag yet.  :woozy_face:  If you have a few minutes to help with that I'd appreciate it.  Otherwise just paste both tags in for now."

2. I had thought that as there are practically no browsers out that that do not support javascript, adding the noscript tag might be an optimisation too far - what do you think, of course it's easy to add if we need?

**Comment by cbetta** [comment]
Agree on both @steve-gr4vy. Fine as is then! Ready to merge when you are ready/

**Pull request merged**
